name: flutter_map_issue
description: Flutter project used to demonstrate the "grid" issue found in a web version opened by a phone

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  archive: ^3.3.7
  cupertino_icons: ^1.0.2
  flutter_map: ^3.1.0
  http: ^0.13.3
  image: ^3.0.2
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/